[pytest]
addopts = -v -s --tb=short --disable-warnings --browser chromium --video=retain-on-failure --alluredir=allure-results
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
